[package]
name = "musikr"
version = "0.1.0"
authors = ["OxygenCobalt <oxycblt@abstractr.net>"]
edition = "2018"
description = "Modify the metadata of music files"
license = "GPL-3.0-or-later"
license-file = "./LICENSE"
readme = "./README.md"

[profile.release]
panic = 'abort'

[dependencies]
